### ISSUE TITLE
Discontinuous Spreading Center in Spherical Models When Passing 180 Lon

### ISSUE THREAD

**Issue by danieldouglas92** [GeodynamicWorldBuilder/WorldBuilder#518] opened 2023-10-20 17:31 UTC
When trying to write a .wb file that contains a mid-ocean ridge that crosses through 180 degree longitude, the ridge truncates at 180. 

I attached the output of an example world builder file that shows how the ridge gets stopped at 180 lon. It shows the temperature at the surface of the model that has dimensions -10 to 10 degrees latitude, and 170 to 190 degrees longitude. The mid ocean ridge should span go from 170 to 190 degrees longitude along the equator, but instead it stops in the center.

![truncated_ridge](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/9e32c18d-3145-45db-8e5c-1c1318230a59)

[MOR_grid.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13056839/MOR_grid.txt)
[MOR_wb.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13056841/MOR_wb.txt)

**Comment by MFraters** [comment] 2023-10-20 17:57
Thanks for reporting this issue, I will take a look at it.

**Comment by MFraters** [comment] 2023-10-20 18:12
For reference, my initial guess is that this is related to, and probably needs a similar fix, as issue #338

**Comment by danieldouglas92** [comment] 2023-10-20 18:38
I tried messing around with the way I define the longitude and and I'm still getting discontinuity across 180.

Here is an example where the ridge coordinates are `[[[-191, 0], [-181, 0], [-179, 0], [-169, 0]]]`:

![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/2d10a685-8fa6-495a-bbf5-4d0d58692880)


And here is an example where the Ridge coordinates are `[[[169, 0], [179, 0], [-179, 0], [-169, 0]]]`:

![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/8b012cb9-b941-406d-adab-bdf602042a73)

**Comment by danieldouglas92** [comment] 2023-10-24 18:57
As a bypass to this issue I thought that I would try just shifting my entire region so that I wouldn't have to deal with crossing the prime meridian. This fixed the issue of the ridge being discontinuous but it seems to have introduced another issue with the temperature being incorrect at depth. 

This is the temperature at the surface showing a continuous ridge:
![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/2e4217b9-5615-4c34-bc2f-5a0161dc0e0f)

But this is the temperature at 10km depth showing a strange vertical temperature anomaly that shouldn't be there:
![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/0cc5f48b-cfe8-46fd-90c5-9afb9416e121)

I attached the .wb file and the .grd file to recreate this model.

[shifted_MOR_grid.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13125998/shifted_MOR_grid.txt)
[shifted_MOR_wb.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13125999/shifted_MOR_wb.txt)

**Comment by danieldouglas92** [comment] 2023-10-24 21:49
Another addition, if the ridge does not cross a longitude of 90, then the vertical feature goes away and the temperature distribution looks correct at the surface and at depth. 

Here is the temperature at the surface:
![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/d9bed407-787f-46bd-ae0f-4477d42ff0f0)

and the temperature at depth:
![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/9e112f80-9647-4193-aa49-c0337befe8a2)

and the grid and wb file to reproduce this.
[do_not_cross_90_grid.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13127745/do_not_cross_90_grid.txt)
[do_not_cross_90_wb.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13127746/do_not_cross_90_wb.txt)

**Comment by MFraters** [comment] 2023-10-27 21:04
I think I fixed the issue, at least partially. The fix is currently quit hacky and not yet there for the transform fault of the ridges.

Below is the old (left) and new (right) result forMOR_wb.txt
![ridge_old_and_fixed](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/7631629/1e4b5053-c27d-4a33-ac4d-fdad53985a76)

**Comment by MFraters** [comment] 2023-11-09 03:52
Sorry it took me so long, but I finally have take a look at the other case as well. It turned out that was caused by a separate problem with the distance computation in spherical coordinates. 

The fix in the half-space cooling model does still need to be ported to other plugins, probably some test results will need to be updated and these two cases need to be added to the test suite.

**Comment by MFraters** [comment] 2024-01-22 21:27
resolved by #520

**Closed by MFraters** 2024-01-22 21:27 UTC
