### ISSUE TITLE
Using sticky air in subduction model

### ISSUE THREAD

**Issue by dipghosh14** [GeodynamicWorldBuilder/WorldBuilder#152] opened 2020-02-22 07:56 UTC
Hi,
I am new to subduction modeling, and I'm trying to develop a 2-D subduction model in ASPECT using GWB. By default the minimum depth of plates matches with the top surface of the model. So I cannot incorporate a layer of sticky air on top of the plates. Is there a way to do this in GWB??
Cheers,
Dip

**Comment by MFraters** [comment] 2020-02-22 22:06
Hey Dip,

Thanks for using the world builder. This is a good question, and I have been playing around a bit to find a satisfactory solution for this problem. The problem is that the world builder expects the surface to be at depth 0, while aspect uses the top of the model as depth zero and passes that to the world builder as the depth. Since some of the temperature models use the depth in their calculations, it difference matters when you want to add a sticky air layer.

I have made a pull request for aspect which fixes the problem (see https://github.com/geodynamics/aspect/pull/3378), but we might end up with another solution. Below are the files which work work with the version of aspect with the pull request. 

I will keep you updated on a solution.

world builder:
```
{
  "version":"0.2",
  "cross section":[[0,0],[100,0]],
  "features":
  [
    {"model":"mantle layer", "name":"sticky air","min depth":-100e3, "max depth":0e3, "coordinates":[[-1e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[-1e3,1e3]],
     "temperature models":[{"model":"uniform", "temperature":5, "min depth":-100e3}],
     "composition models":[{"model":"uniform", "compositions":[6], "min depth":-100e3}]},

    {"model":"oceanic plate", "name":"oceanic plate", "coordinates":[[-1e3,-1e3],[1150e3,-1e3],[1150e3,1e3],[-1e3,1e3]],
     "temperature models":[{"model":"plate model", "max depth":95e3, "bottom temperature":1600, "spreading velocity":0.005, "ridge coordinates":[[100e3,-1e3],[100e3,1e3]]}],
     "composition models":[{"model":"uniform", "compositions":[0], "max depth":10e3},
                           {"model":"uniform", "compositions":[1], "min depth":10e3, "max depth":95e3}]},

    {"model":"continental plate", "name":"continental plate", "coordinates":[[1150e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[1150e3,1e3]],
     "temperature models":[{"model":"linear", "max depth":95e3, "bottom temperature":1600}],
     "composition models":[{"model":"uniform", "compositions":[2], "max depth":30e3},
                           {"model":"uniform", "compositions":[3], "min depth":30e3, "max depth":65e3}]},

    {"model":"mantle layer", "name":"upper mantle", "min depth":95e3, "max depth":660e3, "coordinates":[[-1e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[-1e3,1e3]],
     "temperature models":[{"model":"linear", "min depth":95e3, "max depth":660e3, "top temperature":1600, "bottom temperature":1820}],
     "composition models":[{"model":"uniform", "compositions":[4]}]},

    {"model":"mantle layer", "name":"lower mantle", "min depth":660e3, "max depth":1160e3, "coordinates":[[-1e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[-1e3,1e3]],
     "temperature models":[{"model":"linear", "min depth":660e3, "max depth":1160e3, "top temperature":1820, "bottom temperature":2000}],
     "composition models":[{"model":"uniform", "compositions":[5]}]},

    {"model":"subducting plate", "name":"Subducting plate", "coordinates":[[1150e3,-1e3],[1150e3,1e3]], "dip point":[2000e3,0],
     "segments":[{"length":200e3, "thickness":[95e3], "angle":[0,45]}, {"length":200e3, "thickness":[95e3], "angle":[45]},
                 {"length":200e3, "thickness":[95e3], "angle":[45,0]}, {"length":100e3, "thickness":[95e3], "angle":[0]}],
     "temperature models":[{"model":"plate model", "density":3300, "plate velocity":0.01}],
     "composition models":[{"model":"uniform", "compositions":[0], "max distance slab top":10e3},
                           {"model":"uniform", "compositions":[1], "min distance slab top":10e3, "max distance slab top":95e3 }]}
  ]
}
```

aspect:
```
set Nonlinear solver scheme =no Advection, no Stokes
set World builder file                     = world_builder_subduction_ground_zero.wb
set World builder depth offset = -100e3
set Use years in output instead of seconds = false
set Output directory = wbdir2
set Adiabatic surface temperature = 1613

subsection Boundary velocity model
  set Zero velocity boundary indicators = 1
end

subsection Boundary velocity model
  set Tangential velocity boundary indicators = 0, 2, 3
end

subsection Mesh refinement
  set Initial global refinement = 7
end

subsection Postprocess
  set List of postprocessors = visualization
  subsection Visualization
    set Interpolate output = false
    set List of output variables = adiabat
  end

end

subsection Compositional fields
  set Number of fields = 7
end

subsection Material model
  set Model name = simple
  subsection Simple model
    set Reference temperature = 1613
    set Viscosity = 1e21
    set Thermal conductivity = 1e-06
    set Density differential for compositional field 1 = 500
  end

end

set End time = 0
subsection Geometry model
  set Model name = box
  subsection Box
    set X extent = 2000e3
    set Y extent = 850e3
  end
end

subsection Gravity model
  set Model name = vertical
end

subsection Initial temperature model
  set Model name = world builder
end

subsection Initial composition model
  set List of model names = world builder
end
```

figure of the temperature:
![aspect_world_builder_free_surface](https://user-images.githubusercontent.com/7631629/75099951-56df4580-557c-11ea-8629-13da4737cb85.png)

**Comment by MFraters** [comment] 2020-02-25 18:35
Hey Dip,

A slightly different version of the pull request has been merged. The input file for the world builder has stayed the same, but the aspect prm file has changed a bit. What you need to do is just add a initial topography. An example can be found in the aspect test directory: `tests/world_builder_simple_2d_cartesian_sticky_air.prm`.

Does this awnser your question?

**Comment by dipghosh14** [comment] 2020-03-03 12:36
Thank you for the quick reply.
First of all, I apologize for the delay. I modified my .prm and .wb files according to your suggestions, and now it perfectly constructs my subduction geometry, T and viscosity profiles, etc.. But there is a problem arising while using adaptive mesh refinement. The adaptive meshing does not follow the newly constructed geometry, it rather follows the initial geometry. I'm attaching the figures for your convenience.  
![T](https://user-images.githubusercontent.com/38559890/75775952-084e5a00-5d79-11ea-9740-52634529c66b.jpg)
![mesh](https://user-images.githubusercontent.com/38559890/75775958-0a181d80-5d79-11ea-8510-eee8201113f3.jpg)

**Comment by MFraters** [comment] 2020-03-03 21:06
Hey Dip,
I can see what the problem is and have been able to reproduce it. 
The problem is that the topography is added after the initial mesh refinement. It is easy to fix it, (just changing `if (pre_refinement_step == parameters.initial_adaptive_refinement)` to `if (pre_refinement_step == 0)` around line 1867 in core.cc in aspect, but I am not sure why it was designed like that in the first place, so I made an issue in the aspect repository to ask that (see https://github.com/geodynamics/aspect/issues/3402).

**Comment by lmx08** [comment] 2020-07-25 05:59
Hi,
Any examples of how to visualize the above sticky air model via *.grid file? 

Cheers,
Mengxue

**Comment by MFraters** [comment] 2021-06-26 21:02
I am sorry I am only now seeing this. In case you still need it, you can find an exmple of a .grid file in the [manual](https://gwb.mfraters.net/manual/manual.pdf) in section 3.10. If you have any questions about it, please let me know.

**Closed** 2024-01-23 16:59 UTC
