### ISSUE TITLE
Subduction temperature

### ISSUE THREAD

**Issue by sungho91** [GeodynamicWorldBuilder/WorldBuilder#122] opened 2019-05-16 12:00 UTC
Hello. This is Sungho Lee.

I have a question about the subduction plate model's temperature.

the model requires density and velocity and then they are calculated for initial temp.
But, the temperature of the top surface of subduction has a high temperature.
Is it right?

I think it is something ambiguous.

Thanks

**Comment by MFraters** [comment] 2019-05-16 13:34
Hello Sungho Lee,

Thank you for your question. There are currently four different temperature models implemented for the subducting plate. Based on your description I am guessing you are using the plate model. This uses the temperature model as described in the McKenzie 1970 paper, which indeed has a high temperature at the top of the plate. Depending on your case this may or may not be a good enough approximation. 

If this doesn't work for you there are several ways to fix the problem. You could for example prescribe a temperature in the top part of the slab. An other option is to use (or design) an other temperature model and implement it as a plugin. If you want help with that, please let me know.

**Comment by sungho91** [comment] 2019-05-27 02:15
Hello Fraters 

In advance, thank you for your kind reply and sharing your grateful effort to the public :+1:  .
I'm really new to ASPECT and your Geodynamic World Builder(GWB).
I was struggling to build a flat subduction model and then found your software.
I believe it is lucky.

By the way, this question arises from my original difficulty, I have three temperature zones. 
First is underneath ocean crust, second is on and inside slab, third is underneath the continental crust.

First and second is ok with handling with GWB, but my problem is how to make a gradual thickness increasing lithosphere in lateral direction underneath the continental crust and how to assign temperature on the gradual thickness increasing lithosphere underneath the continental crust.

My idea is making a number of continental plates and they have depth steppings for mimicking gradual thickness increasing lithosphere but this is not a genuine solution, I think.

If you don't mind asking for your experience.
Do you have any idea?

Best regards

Sungho

**Comment by MFraters** [comment] 2019-05-27 03:38
Hey Sungho,

I think your question is related to issue #94. A permanent solution has not been implemented yet, but there are some ways to achieve something like this with the current code. I think 'cleanest' temporary solution is to first set the continental plate and then use a subducting plate of fault with an adiabatic temperature model to cut off the bottom of the continental plate. That way you can get a gradual thickness increase of the continental plate. I hope to soon have the time to work on a more permanent solution.

Does this help?

Cheers,

Menno

**Comment by sungho91** [comment] 2019-05-28 02:53
I catch what you are saying. However, I don't  know how to make lines for a cutting fault for
gradual increasing thickness lithosphere model.

The manual says that lines seem like subduction model, but not enough to fully understand for me.
Would you mind... May I ask for some lines for the cutting fault.

This is mine

{
 "version":"0.2",
 "cross section":[[0,0],[100,0]],
 "features":
 [
  // defining the oceanic plate
  {
  "model":"oceanic plate", "name":"oceanic plate", 
  "coordinates":[[-1e3,-1e3],[1000e3,-1e3],[1000e3,1e3],[-1e3,1e3]],
  "temperature models":
  [
   {"model":"plate model", "max depth":95e3, "bottom temperature":1600,"spreading velocity":0.025,
   "ridge coordinates":[[-1500e3,-1e3],[-1500e3,1e3]]}
  ],
  "composition models":
  [{"model":"uniform", "compositions":[0], "max depth":10e3},
   {"model":"uniform", "compositions":[1], "min depth":10e3,"max depth":95e3}
  ]
  },

  // defining a continental plate
  {
  "model":"continental plate", "name":"continental plate",
  "coordinates":[[1000e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[1000e3,1e3]],
  "temperature models":
  [
  {"model":"linear", "max depth":95e3, "bottom temperature":1600}
  ],
  "composition models":
  [
  {"model":"uniform", "compositions":[2], "max depth":30e3},
  {"model":"uniform", "compositions":[3], "min depth":30e3, "max depth":65e3}
  ]
  },

  // defining the asthenosphere
  {
  "model":"mantle layer", "name":"asthenosphere",
  "min depth":95e3, "max depth":200e3,
  "coordinates":[[-1e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[-1e3,1e3]],
  "temperature models":
  [
  {"model":"linear", "min depth":95e3, "max depth":200e3,"top temperature":1600, "bottom temperature":1640.88}
  ],
  "composition models":[{"model":"uniform", "compositions":[4]}]
  },


  // defining the upper mantle
  {
  "model":"mantle layer", "name":"upper mantle",
  "min depth":200e3, "max depth":660e3,
  "coordinates":[[-1e3,-1e3],[2001e3,-1e3],[2001e3,1e3],[-1e3,1e3]],
  "temperature models":
  [
  {"model":"linear", "min depth":200e3, "max depth":660e3,"top temperature":1640.88, "bottom temperature":1820}
  ],
  "composition models":[{"model":"uniform", "compositions":[5]}]
  },

 
  // defining the subducting plate dipping towards the continental plate
  {
  "model":"subducting plate", "name":"Subducting plate",
  "coordinates":[[1000e3,-1e3],[1000e3,1e3]], "dip point":[4000e3,0],
  "segments":[{"length":200e3, "thickness":[95e3], "angle":[0,25]},
              {"length":50e3, "thickness":[95e3], "angle":[25]},
              {"length":50e3, "thickness":[95e3], "angle":[25,0]},
              {"length":100e3, "thickness":[95e3], "angle":[0]}
              ],
  "temperature models":
  [
  {"model":"plate model", "density":3300, "plate velocity":0.05}
//   {"model":"plate model", "max depth":95e3, "bottom temperature":1600,"spreading velocity":0.025,
//   "ridge coordinates":[[-1500e3,-1e3],[-1500e3,1e3]]}

  ],
  "composition models":
  [
  {"model":"uniform", "compositions":[6], "max distance slab top":10e3},
  {"model":"uniform", "compositions":[1], "min distance slab top":10e3, "max distance slab top":95e3 }
  ]            
  },
 
**#  {
#  "model":"fault", "name":"a fault",???
#  },**

  {
   "model":"continental plate", "name":"top on slab", "max depth":1,
   "coordinates":[[900e3,-1e3],[1100e3,-1e3],[1100e3,1e3],[900e3,1e3]],
   "temperature models":[{"model":"uniform", "temperature":293}]
  }


 ]
}

**Comment by MFraters** [comment] 2019-05-29 15:37
I haven't tested it, but I would say at the place where you now have the fault in bold you have to put something like this:

```
{
  "model": "subducting", "name":"workaround: create passive margin", "max depth":100e3,
  "coordinates":[[?,?],[?,?],...],
  "segments":[{"length":300e3, "thickness":[100e3], "angle":[45]}],
  "temperature models":[{model":adiabatic"}]
}
```

Does this work for you?

**Comment by MFraters** [comment] 2019-09-16 01:39
I am assuming the issue is sovled, so I am closing it. If not, feel free to reopen or make a new issue.

**Closed by MFraters** 2019-09-16 01:39 UTC
