### ISSUE TITLE
A dummy question :  spreading velocity and plate velocity

### ISSUE THREAD

**Issue by sungho91** [GeodynamicWorldBuilder/WorldBuilder#126] opened 2019-07-01 07:58 UTC
Hello.

I have a question about "spreading velocity and plate velocity in parameter".
Are they same or different (spreading velocity= half*plate velocity)? 

sungho

**Comment by MFraters** [comment] 2019-07-01 20:22
Hey Sungho,

Thank you for you question. I am guessing that you mean the `spreading velocity` parameter of the `oceanic plate` `plate model` and the `plate velocity` parameter of the `subducting plate` `plate model`.

The `subducting plate` `plate model` `plate velocity` is conceptually how fast the plate is doing down, and in practice it is used in the McKenzie 1970 temperature model for a down going slab. 

The `oceanic plate` `plate model` `spreading velocity` is just a simple half space model (I can't remember a ref now, but it is something you can find in the book `The solid Earth` (ISBN-13: 978-0521893077). This `spreading velocity` is the velocity with which each half of the plate moves. 

So in practice you probably want to set the `subducting plate` `plate velocity` equal to the `oceanic plate` `spreading velocity`. 

Does this help? Also if issue #122 is solved, could you close the issue?

Best,

Menno

**Comment by MFraters** [comment] 2019-09-16 01:39
I am assuming the issue is sovled, so I am closing it. If not, feel free to reopen or make a new issue.

**Closed by MFraters** 2019-09-16 01:39 UTC
